<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHwRNImp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHwRNImp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHwRNImp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHwRNImp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHwRNImp\App_KernelDevDebugContainer([
    'container.build_hash' => 'HwRNImp',
    'container.build_id' => 'a96e789b',
    'container.build_time' => 1704286945,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHwRNImp');
