<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOX5xMCX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOX5xMCX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOX5xMCX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOX5xMCX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOX5xMCX\App_KernelDevDebugContainer([
    'container.build_hash' => 'OX5xMCX',
    'container.build_id' => 'afce8da4',
    'container.build_time' => 1704286517,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOX5xMCX');
